server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: bitweb
    password: dkdlxl123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    database: mysql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      hibernate: info

upload:
  path: /home/oem/upload

#upload.path=C:/upload