server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?serverTimezone=UTC&useSSL=false
    username: bitweb
    password: dkdlxl123
    driver-class-name: com.mysql.cj.jdbc.Driver